name: Bai 5 - JaCoCo Coverage

on:
  push:
    branches: [ "main" ]
    # 1. Chỉ kích hoạt workflow này nếu có thay đổi trong thư mục b5
    paths:
      - 'b5/**'
  pull_request:
    branches: [ "main" ]
    paths:
      - 'b5/**'

jobs:
  build:
    runs-on: ubuntu-latest

    # 2. Bắt buộc mọi lệnh 'run' ở dưới phải chui vào thư mục b5 để chạy
    defaults:
      run:
        working-directory: ./b5

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up JDK 17
        uses: actions/setup-java@v4
        with:
          java-version: '17'
          distribution: 'temurin'
          cache: maven

      # Lệnh này bây giờ sẽ thực thi bên trong thư mục ./b5
      - name: Run test and verify coverage
        run: mvn clean verify

      # 3. Phải cập nhật lại đường dẫn lấy file report cho đúng
      - name: Upload JaCoCo Coverage Report
        uses: actions/upload-artifact@v4
        if: always()
        with:
          name: jacoco-report-b5
          path: b5/target/site/jacoco/ # Cập nhật đường dẫn có chứa thư mục b5
          retention-days: 7